### ISSUE TITLE
Decode a broadcasted message 

### ISSUE THREAD

**Issue by whiteyhat** [Blockstream/satellite-api#8]
Hey, currently when using `GET /order/:uuid` the only parameter related with the received data is the `message_diggest`

Is it required this python example to decode and read the data broadcasted? 

How can I decode and read broadcasted data from the satellite API using the `uuid` and the `authToken` in JavaScript?

 @bteitelb @nbenoit

**Comment by bteitelb** [comment]
@whiteyhat this API is only for ordering and sending satellite transmissions. To decode broadcast data, use the Python scripts over at: https://github.com/Blockstream/satellite I see you have created an issue over there requesting help.
